name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Clone the GitHub repository
        uses: actions/checkout@v4
      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: "npm"
      - name: Install program dependencies
        run: npm install
      - name: Start the app
        run: npm run start
      - name: Test the app
        run: npm run test
