name: Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x. 20.x, 21.x]
    steps:
      - name: Clone the GitHub repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install program dependencies
        run: npm install
      - name: Start the app
        run: npm run start &
      - name: Test the app
        run: npm run test
